version: '3'
services:
  fibonacci:
    build: ./
    ports:
      - "8080:80"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: https://otlp.nr-data.net:4317
      OTEL_EXPORTER_OTLP_HEADERS: "api-key=${NEW_RELIC_API_KEY}"
  load-generator:
    build: ./load-generator
